version: '3'
services:
  db:
    image: mysql
    container_name: mysql_db
    restart: always
    volumes:
      - data:/var/lib/mysql
    env_file:
      - .env.example
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_backend
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    depends_on:
      - db
volumes:
  data: